import Foundation
import SwiftData

/// Coordinates account lifecycle between SwiftData (metadata) and Keychain (credentials).
///
/// This manager ensures atomic operations when creating, updating, or removing accounts.
/// For Nextcloud accounts, it pairs a `ServerAccount` record in SwiftData with a password
/// entry in the Keychain. For Vault Mode accounts, no Keychain entry is created.
///
/// **Usage:**
/// ```swift
/// let manager = AccountManager(modelContext: context)
/// // Vault mode
/// try await manager.createVaultAccount()
/// // Nextcloud
/// try await manager.addNextcloudAccount(...)
/// // Promote vault → nextcloud
/// try await manager.promoteToNextcloud(accountID: ..., ...)
/// ```
@MainActor
final class AccountManager: Observable {

    private let modelContext: ModelContext
    private let keychainManager: KeychainManager

    init(modelContext: ModelContext, keychainManager: KeychainManager = KeychainManager()) {
        self.modelContext = modelContext
        self.keychainManager = keychainManager
    }

    // MARK: - Vault Mode

    /// Creates a local-only Vault Mode account with a default "Inbox" task list.
    ///
    /// No Keychain entry is created since Vault Mode requires no credentials.
    /// - Parameter displayName: The user-facing name for the vault. Defaults to "Vault".
    /// - Returns: The created `ServerAccount`.
    @discardableResult
    func createVaultAccount(displayName: String = "Vault") throws -> ServerAccount {
        let account = ServerAccount(vaultDisplayName: displayName)
        modelContext.insert(account)

        // Create a default "Inbox" list for the vault
        let inbox = TaskList(
            serverURL: "",
            name: String(localized: "Inbox"),
            colorHex: "#007AFF"
        )
        inbox.account = account
        modelContext.insert(inbox)

        try modelContext.save()
        return account
    }

    // MARK: - Nextcloud

    /// Creates a Nextcloud account with credentials stored in the Keychain.
    ///
    /// This is an atomic operation: if the Keychain save fails, the SwiftData
    /// record is not persisted.
    ///
    /// - Parameters:
    ///   - displayName: User-facing account name (e.g., "Work Cloud").
    ///   - serverURL: The base URL of the Nextcloud server.
    ///   - username: The Nextcloud username.
    ///   - password: The app-password for CalDAV authentication.
    ///   - storeInKeychain: Whether to persist the password in the Keychain. Defaults to `true`.
    /// - Returns: The created `ServerAccount`.
    @discardableResult
    func addNextcloudAccount(
        displayName: String,
        serverURL: String,
        username: String,
        password: String,
        storeInKeychain: Bool = true
    ) async throws -> ServerAccount {
        let account = ServerAccount(
            displayName: displayName,
            serverBaseURL: serverURL,
            username: username,
            mode: .nextcloud
        )
        modelContext.insert(account)

        if storeInKeychain {
            try await keychainManager.save(password: password, for: account.id)
        }

        do {
            try modelContext.save()
        } catch {
            try? await keychainManager.delete(for: account.id)
            throw error
        }
        return account
    }

    /// Creates a Nextcloud account from Login Flow v2 credentials.
    ///
    /// The app password was generated by the server during the Login Flow,
    /// so the `authMethod` is set to `.loginFlow` for UI differentiation.
    ///
    /// - Parameters:
    ///   - serverURL: The base URL returned by the Login Flow.
    ///   - loginName: The username returned by the Login Flow.
    ///   - appPassword: The server-generated app password.
    /// - Returns: The created `ServerAccount`.
    @discardableResult
    func addNextcloudAccountViaLoginFlow(
        serverURL: String,
        loginName: String,
        appPassword: String
    ) async throws -> ServerAccount {
        let account = ServerAccount(
            displayName: loginName,
            serverBaseURL: serverURL,
            username: loginName,
            mode: .nextcloud
        )
        account.storedAuthMethod = .loginFlow
        modelContext.insert(account)

        try await keychainManager.save(password: appPassword, for: account.id)

        do {
            try modelContext.save()
        } catch {
            try? await keychainManager.delete(for: account.id)
            throw error
        }
        return account
    }


    /// Promotes a Vault Mode account to Nextcloud by adding server details and credentials.
    ///
    /// All existing local task lists and tasks are preserved and will begin syncing
    /// once the sync engine connects.
    ///
    /// - Parameters:
    ///   - accountID: The ID of the existing Vault account to promote.
    ///   - serverURL: The Nextcloud server base URL.
    ///   - username: The Nextcloud username.
    ///   - password: The app-password for CalDAV authentication.
    func promoteToNextcloud(
        accountID: String,
        serverURL: String,
        username: String,
        password: String
    ) async throws {
        let targetID = accountID
        let predicate = #Predicate<ServerAccount> { $0.id == targetID }
        var descriptor = FetchDescriptor<ServerAccount>(
            predicate: predicate
        )
        descriptor.fetchLimit = 1

        guard let account = try modelContext.fetch(descriptor).first else {
            return
        }

        account.mode = .nextcloud
        account.serverBaseURL = serverURL
        account.username = username
        account.displayName = username

        try await keychainManager.save(password: password, for: account.id)
        try modelContext.save()
    }

    /// Updates an existing Nextcloud account's settings.
    ///
    /// Only non-nil parameters are applied, allowing partial updates.
    /// If a new password is provided, the Keychain entry is replaced.
    ///
    /// - Parameters:
    ///   - accountID: The ID of the account to update.
    ///   - displayName: Optional new display name.
    ///   - serverURL: Optional new server base URL.
    ///   - username: Optional new username.
    ///   - password: Optional new app-password (updates Keychain if provided).
    func updateNextcloudAccount(
        accountID: String,
        displayName: String? = nil,
        serverURL: String? = nil,
        username: String? = nil,
        password: String? = nil
    ) async throws {
        let targetID = accountID
        let predicate = #Predicate<ServerAccount> { $0.id == targetID }
        var descriptor = FetchDescriptor<ServerAccount>(
            predicate: predicate
        )
        descriptor.fetchLimit = 1

        guard let account = try modelContext.fetch(descriptor).first else {
            return
        }

        if let displayName = displayName {
            account.displayName = displayName
        }
        if let serverURL = serverURL {
            account.serverBaseURL = serverURL
        }
        if let username = username {
            account.username = username
        }
        if let password = password {
            try await keychainManager.save(password: password, for: account.id)
        }

        try modelContext.save()
    }

    // MARK: - Account Removal

    /// Removes an account and its associated Keychain credentials.
    ///
    /// SwiftData cascade rules will delete all associated task lists and tasks.
    /// - Parameter accountID: The ID of the account to remove.
    func removeAccount(accountID: String) async throws {
        let targetID = accountID
        let predicate = #Predicate<ServerAccount> { $0.id == targetID }
        var descriptor = FetchDescriptor<ServerAccount>(
            predicate: predicate
        )
        descriptor.fetchLimit = 1

        guard let account = try modelContext.fetch(descriptor).first else {
            return
        }

        // Preserve never-synced (local-only) tasks before the cascade delete so
        // removing an account can't destroy work that exists nowhere else.
        try preserveUnsyncedTasks(of: account)

        // Remove Keychain entry (idempotent — safe for Vault accounts too)
        try await keychainManager.delete(for: account.id)

        modelContext.delete(account)
        try modelContext.save()
    }

    /// Moves the account's never-synced tasks into a local Vault "Recovered Tasks"
    /// list so they survive removal. A task is considered never-synced when it has
    /// no `remoteHref` (never created on or pulled from the server). Synced tasks
    /// remain safe on the server and are removed with the account.
    private func preserveUnsyncedTasks(of account: ServerAccount) throws {
        let accID = account.id
        let listPredicate = #Predicate<TaskList> { $0.account?.id == accID }
        let lists = (try? modelContext.fetch(FetchDescriptor<TaskList>(predicate: listPredicate))) ?? []

        var unsynced: [TaskItem] = []
        for list in lists {
            let listID = list.id
            let taskPredicate = #Predicate<TaskItem> {
                $0.taskList?.id == listID && !$0.isDeletedLocally
            }
            let tasks = (try? modelContext.fetch(FetchDescriptor<TaskItem>(predicate: taskPredicate))) ?? []
            unsynced.append(contentsOf: tasks.filter { ($0.remoteHref ?? "").isEmpty })
        }

        guard !unsynced.isEmpty else { return }

        let recoveryList = try findOrCreateRecoveryList(excludingAccountID: accID)
        let preservedIDs = Set(unsynced.map(\.id))
        for task in unsynced {
            // Detach from a parent that won't be preserved so the parentTask
            // cascade can't delete this task along with the removed account.
            if let parent = task.parentTask, !preservedIDs.contains(parent.id) {
                task.parentTask = nil
            }
            task.taskList = recoveryList
        }
        try modelContext.save()
    }

    /// Returns a Vault "Recovered Tasks" list to hold preserved tasks, creating
    /// the Vault account and/or the list if needed. Never reuses the account
    /// currently being removed.
    private func findOrCreateRecoveryList(excludingAccountID: String) throws -> TaskList {
        let allAccounts = (try? modelContext.fetch(FetchDescriptor<ServerAccount>())) ?? []
        let vault: ServerAccount
        if let existing = allAccounts.first(where: { $0.mode == .vault && $0.id != excludingAccountID }) {
            vault = existing
        } else {
            vault = ServerAccount(vaultDisplayName: String(localized: "Recovered"))
            modelContext.insert(vault)
        }

        let recoveryName = String(localized: "Recovered Tasks")
        if let existing = vault.taskLists.first(where: { $0.name == recoveryName }) {
            return existing
        }
        let list = TaskList(serverURL: "", name: recoveryName, colorHex: "#007AFF")
        list.account = vault
        modelContext.insert(list)
        return list
    }

    // MARK: - Credential Access

    /// Retrieves stored credentials for a Nextcloud account.
    ///
    /// - Parameter accountID: The ID of the account.
    /// - Returns: A tuple of `(username, password)`, or `nil` if not found.
    func getCredentials(for accountID: String) async throws -> (username: String, password: String)? {
        let targetID = accountID
        let predicate = #Predicate<ServerAccount> { $0.id == targetID }
        var descriptor = FetchDescriptor<ServerAccount>(
            predicate: predicate
        )
        descriptor.fetchLimit = 1

        guard let account = try modelContext.fetch(descriptor).first,
              account.mode == .nextcloud else {
            return nil
        }

        guard let password = try await keychainManager.retrieve(for: account.id) else {
            return nil
        }

        return (account.username, password)
    }
}
